spring.application.name=devspring

# 타임리프 설정
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# port 설정
server.port=8080

# session timout 설정
server.servlet.session.timeout=30m

# 데이터베이스 연결 설정
# 서태우 집
spring.datasource.driver=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/ceratrust?serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Aa123123!
spring.datasource.mapper-locations=classpath:/static/mapper/*.xml

# 서태우 맥북
#spring.datasource.driver=com.mysql.cj.jdbc.Driver
#spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/ceratrust?serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=Aa123123!
#spring.datasource.mapper-locations=classpath:/static/mapper/*.xml

# MyBatis 기본 설정
mybatis.type-aliases-package=com.spring.devspring.mapper
# 매퍼 XML 경로
mybatis.mapper-locations=classpath:static/mapper/*.xml
# 스네이크 케이스 -> 카멜 케이스 자동 변환
mybatis.configuration.map-underscore-to-camel-case=true

# Logging level 설정
logging.level.org.apache.ibatis=DEBUG
logging.level.org.mybatis.spring=DEBUG
logging.level.com.spring.devspring.mapper=DEBUG

# 카카오 디벨롭 키
kakao.api.key=e20bddeab3ba1f6798e1a20d665e3e9a

# 메일 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aatjxodn22@gmail.com
spring.mail.password=hdnx alff tkvm nyih
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
mail.receiver=aatjxodn22@gmail.com
